// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPeLwcr7rdqNa4GzG0BhbksVVOzg_orPc',
    appId: '1:842724578520:web:8055077b55380fb56ff3ad',
    messagingSenderId: '842724578520',
    projectId: 'elfaa-2023',
    authDomain: 'elfaa-2023.firebaseapp.com',
    storageBucket: 'elfaa-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0gdiL3MAGraFsgHwrzPxkQkmQIbcUldI',
    appId: '1:842724578520:android:03906fa7427f74526ff3ad',
    messagingSenderId: '842724578520',
    projectId: 'elfaa-2023',
    storageBucket: 'elfaa-2023.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTZ9sJ2hZdwQ_LgfTjHGJJkIyz82vsUK8',
    appId: '1:842724578520:ios:6f7dc95590e295736ff3ad',
    messagingSenderId: '842724578520',
    projectId: 'elfaa-2023',
    storageBucket: 'elfaa-2023.appspot.com',
    iosClientId: '842724578520-0kbs78pbmqb04keov1d6n1oodttkvujc.apps.googleusercontent.com',
    iosBundleId: 'com.elfaa.elfaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTZ9sJ2hZdwQ_LgfTjHGJJkIyz82vsUK8',
    appId: '1:842724578520:ios:6f7dc95590e295736ff3ad',
    messagingSenderId: '842724578520',
    projectId: 'elfaa-2023',
    storageBucket: 'elfaa-2023.appspot.com',
    iosClientId: '842724578520-0kbs78pbmqb04keov1d6n1oodttkvujc.apps.googleusercontent.com',
    iosBundleId: 'com.elfaa.elfaa',
  );
}
