// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAijetBQIwgjLkeeQGTIa3l8M9kWJd3aNs',
    appId: '1:856735458268:web:614bdde2b71ebfa9bc2519',
    messagingSenderId: '856735458268',
    projectId: 'elfaa-2022',
    authDomain: 'elfaa-2022.firebaseapp.com',
    storageBucket: 'elfaa-2022.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWPS2OpiWFwsv3UaGFMLFZk241XqYA6Qw',
    appId: '1:856735458268:android:82f1b8cec3ad0b2dbc2519',
    messagingSenderId: '856735458268',
    projectId: 'elfaa-2022',
    storageBucket: 'elfaa-2022.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqFALOZZsAV7rdA92W44BWn9-JY6sMtjc',
    appId: '1:856735458268:ios:1ec33a4991ada537bc2519',
    messagingSenderId: '856735458268',
    projectId: 'elfaa-2022',
    storageBucket: 'elfaa-2022.appspot.com',
    iosClientId: '856735458268-nnhu4mlq5gudi2idpf7ivte5mpheam75.apps.googleusercontent.com',
    iosBundleId: 'com.example.elfaa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqFALOZZsAV7rdA92W44BWn9-JY6sMtjc',
    appId: '1:856735458268:ios:1ec33a4991ada537bc2519',
    messagingSenderId: '856735458268',
    projectId: 'elfaa-2022',
    storageBucket: 'elfaa-2022.appspot.com',
    iosClientId: '856735458268-nnhu4mlq5gudi2idpf7ivte5mpheam75.apps.googleusercontent.com',
    iosBundleId: 'com.example.elfaa',
  );
}
